### PR TITLE
Velocity tests

### PR DESCRIPTION
**Pull request by grey277**
PR #110 + change to make velocity tests pass

### CODE REVIEW

**Comment by grey277** [comment]
run velocity tests

**Comment by wkrzemien** [comment]
So do I understand correctly that this should be accepted after Velocity Calib PR, and then the tests should  be ok?

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
Not, it should pass even though Velocity Calib PR is not accepted. In this PR there are same changes that in Velocity Calib PR + changes to make velocity test pass. I forgot to change 1 path, now it should pass.

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Pull request closed without merging**
