### PR TITLE
Changed speed of light units to cm/ps

### PR DESCRIPTION
**Pull request by Alvarness**

### CODE REVIEW

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: root-6-cppcheck
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-6/LargeBarrelAnalysis/EventCategorizerTools.cpp L239

The function &#39;calculateTOFByConvention&#39; is never used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a261591681>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: root-5-cppcheck
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/LargeBarrelAnalysis/EventCategorizerTools.cpp L239

The function &#39;calculateTOFByConvention&#39; is never used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2121050336>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by grey277** [comment]
Line before: 
double EventCategorizerTools::calculateTOFByConvention(const JPetHit& hitA, const JPetHit& hitB)
please add:
// cppcheck-suppress unusedFunction
to supress cppcheck

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: root-6-cppcheck
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-6/LargeBarrelAnalysis/EventCategorizerTools.cpp L239

The function &#39;calculateTOFByConvention&#39; is never used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a261591681>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 1 violations:

**Reporter**: root-5-cppcheck
**Rule**: unusedFunction
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/LargeBarrelAnalysis/EventCategorizerTools.cpp L239

The function &#39;calculateTOFByConvention&#39; is never used.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-2121050336>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by wkrzemien** [comment]
retest it, please

**Pull request merged**
