### PR TITLE
Velocity calibration unit tests

### PR DESCRIPTION
**Pull request by grey277**
Add mount volume for velocity calibration unit tests, refactor docker entry-point script to use function for call execution, add test for velocity calibration

### CODE REVIEW

**Comment by grey277** [comment]
retest this please

**Comment by grey277** [comment]
retest this please

**Comment by grey277** [comment]
retest this please

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by wkrzemien** [comment]
Is something still missing?

**Comment by grey277** [comment]
Yes, unfortunately bash have big problem dealing with floating points, I changed comparing script to python and I hope now every think will be ok.

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Comment by grey277** [comment]
run velocity tests

**Pull request merged**
