### PR TITLE
Add example with user-defined data class

### PR DESCRIPTION
**Pull request by alekgajos**
This PR adds a new example demonstrating how to include a user-defined data class to be stored in the output files of the framework-based programs.

The approach employed here is intended to replace the idea of including custom classes in the framework core as first tried [in this PR to core](https://github.com/JPETTomography/j-pet-framework/pull/192).

**Note: This PR is specific to the old CMake configuration. It needs to be partially redone after merging of #129 and it should not be considered until then.**

### CODE REVIEW

**Comment by JPETTomographyTester** [comment]
Found 4 violations:

**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/JPetLORevent.h L34

Class &#39;JPetLORevent&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1598370195>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/LORFinder.h L34

Class &#39;LORFinder&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-652823764>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/JPetLORevent.h L34

Class &#39;JPetLORevent&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1598370197>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/LORFinder.h L34

Class &#39;LORFinder&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-652823759>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by JPETTomographyTester** [comment]
Found 4 violations:

**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/JPetLORevent.h L34

Class &#39;JPetLORevent&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1598370195>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/LORFinder.h L34

Class &#39;LORFinder&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-652823764>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/JPetLORevent.h L34

Class &#39;JPetLORevent&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a1598370197>*
**Reporter**: root-5-cppcheck
**Rule**: noExplicitConstructor
**Severity**: INFO
**File**: /var/jenkins_home/workspace/j-pet-framework-examples-PRs-root-5/UserDataClassExample/LORFinder.h L34

Class &#39;LORFinder&#39; has a constructor with 1 argument that is not explicit. Such constructors should in general be explicit for type safety reasons. Using the explicit keyword in the constructor means some mistakes when using the class can be avoided.


*<this is a auto generated comment from violation-comments-lib F7F8ASD8123FSDF>* *<a-652823759>*
 *<ACCUMULATED-VIOLATIONS>*

**Comment by alekgajos** [comment]
please retest this

**Comment by alekgajos** [comment]
retest this please

**Comment by alekgajos** [comment]
Replaced by #140

**Pull request closed without merging**
